export default {
  IND: [
    "Rohit Sharma",
    "KL Rahul",
    "Virat Kohli",
    "Suryakumar Yadav",
    "Rishabh Pant",
    "Hardik Pandya",
    "Ravindra Jadeja",
    "Bhuvneshwar Kumar",
    "Jasprit Bumrah",
    "Yuzvendra Chahal",
    "Mohammed Shami",
  ],
  AUS: [
    "Aaron Finch",
    "David Warner",
    "Steven Smith",
    "Glenn Maxwell",
    "Marcus Stoinis",
    "Matthew Wade",
    "Pat Cummins",
    "Mitchell Starc",
    "Adam Zampa",
    "Josh Hazlewood",
    "Kane Richardson",
  ],
  ENG: [
    "Jos Buttler",
    "Jason Roy",
    "Dawid Malan",
    "Jonny Bairstow",
    "Eoin Morgan",
    "Moeen Ali",
    "Chris Woakes",
    "Adil Rashid",
    "Mark Wood",
    "Jofra Archer",
    "Liam Livingstone",
  ],
  NZ: [
    "Martin Guptill",
    "Kane Williamson",
    "Devon Conway",
    "Glenn Phillips",
    "James Neesham",
    "Daryl Mitchell",
    "Mitchell Santner",
    "Tim Southee",
    "Trent Boult",
    "Ish Sodhi",
    "Kyle Jamieson",
  ],
  PAK: [
    "Babar Azam",
    "Mohammad Rizwan",
    "Fakhar Zaman",
    "Shoaib Malik",
    "Asif Ali",
    "Shadab Khan",
    "Imad Wasim",
    "Shaheen Afridi",
    "Haris Rauf",
    "Hasan Ali",
    "Mohammad Nawaz",
  ],
  RSA: [
    "Quinton de Kock",
    "Temba Bavuma",
    "Aiden Markram",
    "Rassie van der Dussen",
    "David Miller",
    "Heinrich Klaasen",
    "Kagiso Rabada",
    "Anrich Nortje",
    "Lungi Ngidi",
    "Tabraiz Shamsi",
    "Keshav Maharaj",
  ],
  SL: [
    "Kusal Perera",
    "Pathum Nissanka",
    "Charith Asalanka",
    "Avishka Fernando",
    "Bhanuka Rajapaksa",
    "Dasun Shanaka",
    "Wanindu Hasaranga",
    "Dushmantha Chameera",
    "Maheesh Theekshana",
    "Chamika Karunaratne",
    "Lahiru Kumara",
  ],
  WI: [
    "Chris Gayle",
    "Evin Lewis",
    "Nicholas Pooran",
    "Shimron Hetmyer",
    "Kieron Pollard",
    "Andre Russell",
    "Dwayne Bravo",
    "Jason Holder",
    "Obed McCoy",
    "Akeal Hosein",
    "Ravi Rampaul",
  ],
  BAN: [
    "Liton Das",
    "Soumya Sarkar",
    "Shakib Al Hasan",
    "Mushfiqur Rahim",
    "Mahmudullah",
    "Afif Hossain",
    "Mohammad Saifuddin",
    "Mustafizur Rahman",
    "Taskin Ahmed",
    "Mehidy Hasan",
    "Shoriful Islam",
  ],
  AFG: [
    "Hazratullah Zazai",
    "Mohammad Shahzad",
    "Rahmanullah Gurbaz",
    "Najibullah Zadran",
    "Mohammad Nabi",
    "Gulbadin Naib",
    "Rashid Khan",
    "Mujeeb Ur Rahman",
    "Hamid Hassan",
    "Karim Janat",
    "Naveen-ul-Haq",
  ],
};
